// Code generated by goctl. DO NOT EDIT.
package types

type GeneralRequest struct {
}

type GeneralResponse struct {
	Code string `json:"code"` //返回状态 0:成功 | 2:失败
	Msg  string `json:"msg"`  //code对应信息
}
